services:
  allium-db:
    container_name: allium-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-alium}
    volumes:
      - allium_postgres_data:/var/lib/postgresql/data
    # Мы не пробрасываем порт 5432 наружу, чтобы не конфликтовать с другими БД.
    # Приложение будет подключаться внутри сети Docker.

  allium-app:
    container_name: allium-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000" # Используем 3001 на хосте, так как 3000 может быть занят
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-password}@allium-db:5432/${DB_NAME:-alium}?schema=public
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3001}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your_secret_here}
    depends_on:
      - allium-db

volumes:
  allium_postgres_data:
