services:
  alium-postgres:
    container_name: alium-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Allium1380@}
      POSTGRES_DB: ${DB_NAME:-alium}
    volumes:
      - allium_postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5432" # Пробрасываем на 54321, как у пользователя

volumes:
  allium_postgres_data:
